openapi: 3.0.1
servers:
  - description: 로컬 서버
    url: localhost:8080
info:
  description: Closest의 API 명세서입니다.
  version: 0.0.1
  title: Closest API Specification
tags:
  - name: subscriptionQuery
    description: 구독 정보 조회
  - name: subscriptionVisit
    description: 구독 블로그 방문
  - name: subscriptionRegister
    description: 구독 블로그 추가 및 삭제
  - name: myBlogEdit
    description: 나의 블로그 상태 관리
  - name: post
    description: 포스트 관리
  - name: blogAuth
    description: 블로그 인증 관리
paths:
  /subscriptions/blogs/close:
    get:
      tags:
        - subscriptionQuery
      summary: 사용자는 친밀도 순위가 높은 20개의 블로그 목록을 요청
      responses:
        "200":
          description: 구독한 블로그 정보 목록
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SubscriptionResponse'
        "400":
          $ref: '#/components/responses/BadRequest'
        "500":
          $ref: '#/components/responses/InternalServerError'
        "502":
          description: RSS 서버 에러

  /subscriptions/blogs:
    get:
      tags:
        - subscriptionQuery
      summary: 사용자는 구독한 블로그 목록을 요청
      parameters:
        - in: query
          name: page
          required: false
          schema:
            type: integer
            example: 1
          description: 페이지 번호
        - in: query
          name: size
          required: false
          schema:
            type: integer
            example: 10
          description: 페이지당 항목 수
      responses:
        "200":
          description: 구독한 블로그 정보 목록
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SubscriptionResponse'
        "400":
          $ref: '#/components/responses/BadRequest'
        "500":
          $ref: '#/components/responses/InternalServerError'
        "502":
          description: RSS 서버 에러

  /subscriptions:
    post:
      tags:
        - subscriptionRegister
      summary: 사용자가 특정 블로그를 구독 요청
      description: 블로그 URI을 통해 사용자가 구독을 생성한다.
      requestBody:
        description: 구독할 블로그의 URI 정보
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                rssUri:
                  type: string
                  format: uri
                  example: "https://example.com/blog123"
                  description: 구독할 블로그의 URI
      responses:
        "201":
          description: 구독 생성 성공
        "400":
          $ref: '#/components/responses/BadRequest'
        "500":
          $ref: '#/components/responses/InternalServerError'
        "502":
          description: RSS 서버 에러

  /subscriptions/{subscriptionsId}:
    delete:
      tags:
        - subscriptionRegister
      summary: 사용자가 특정 블로그 구독 해지 요청
      description: 구독 정보 키로 사용자와 블로그 연관관계 삭제
      parameters:
        - in: path
          name: subscriptionsId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: 구독 해지 성공
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalServerError'

  /subscriptions/{subscriptionsId}/visit:
    patch:
      tags:
        - subscriptionVisit
      summary: 구독한 블로그 방문 및 조회수 증가
      description: 구독한 블로그는 새창으로 띄우고 해당 구독 정보에 조회수를 1 증가시킨다
      parameters:
        - in: path
          name: subscriptionsId
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: 블로그 방문 성공 및 조회수 증가
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalServerError'

  /my-blog/status:
    patch:
      tags:
        - myBlogEdit
      summary: 자신의 블로그에 다른 유저들이 볼 수 있는 상태 메시지 설정
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      responses:
        "200":
          description: 상태 메시지 생성 성공
        "400":
          $ref: '#/components/responses/BadRequest'
        "403":
          $ref: '#/components/responses/Forbidden'
        "500":
          $ref: '#/components/responses/InternalServerError'

  /posts/like:
    post:
      tags:
        - postLike
      summary: 사용자는 블로그 포스트에 좋아요 생성
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                postUri:
                  type: string
                  format: uri
      responses:
        "200":
          description: 좋아요 생성 성공
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalServerError'

  /blog/auth/message:
    get:
      tags:
        - blogAuth
      summary: 블로그 인증 메시지 생성
      description: 블로그 인증을 위해 랜덤 메시지 생성 요청
      parameters:
        - in: query
          name: rssUri
          required: true
          schema:
            type: string
            format: uri
      responses:
        "200":
          description: 메시지 생성 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthMessageResponse'
        "500":
          $ref: '#/components/responses/InternalServerError'

  /blog/auth/verification:
    post:
      tags:
        - blogAuth
      summary: 블로그 인증 요청
      description: 본인 블로그 구독한 사람을 추적하거나 본인의 블로그에 해당하는 좋아하는 것 추적하기 위해. 나의 블로그를 구독한 사람들에 대한 기능을 만들기 어렵다. 나의 블로그임을 입증한다. 상태메세지나 나를 구독한 사람을 알기 위해서 필요.
      responses:
        "200":
          description: 인증 요청 성공
        "401":
          $ref: '#/components/responses/Unauthorized'
        "500":
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    SubscriptionResponse:
      type: object
      properties:
        subscriptionId:
          type: integer
          format: int64
          example: 1
        nickName:
          type: string
          example: 개발자123
        uri:
          type: string
          format: uri
          example: https://example.com/blog1
        newPostsCnt:
          type: integer
          example: 5
        visitCnt:
          type: integer
          format: int64
          example: 1
        publishedDateTime:
          type: string
          format: date-time
          example: 2023-12-12T10:15:30

    AuthMessageResponse:
      type: object
      properties:
        authMessage:
          type: string
          example: "AB12CD34EF56"

  responses:
    BadRequest:
      description: 올바르지 않은 요청
    Unauthorized:
      description: 인증 실패
    Forbidden:
      description: 요청한 사용자 정보가 일치하지 않음
    NotFound:
      description: 리소스를 찾을 수 없음
    InternalServerError:
      description: 서버 에러
